---
openapi: 3.0.1
info:
  title: API V1
  version: v1
  description: This is the API documentation for the Copper API
paths:
  "/api/v1/contacts":
    get:
      summary: List contacts
      tags:
      - Contacts
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: integer
      - name: per_page
        in: query
        required: false
        schema:
          type: integer
      responses:
        '200':
          description: contacts found
          content:
            application/json:
              schema:
                type: object
                properties:
                  contacts:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        email:
                          type: string
                        created_at:
                          type: string
                          format: date_time
                        updated_at:
                          type: string
                          format: date_time
                  total_pages:
                    type: integer
                  current_page:
                    type: integer
                  total_entries:
                    type: integer
    post:
      summary: Create a contact
      tags:
      - Contacts
      parameters: []
      responses:
        '201':
          description: contact created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                contact:
                  type: object
                  properties:
                    name:
                      type: string
                    email:
                      type: string
                  required:
                  - name
                  - email
  "/api/v1/contacts/{id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
    get:
      summary: Show a contact
      tags:
      - Contacts
      responses:
        '200':
          description: contact found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  email:
                    type: string
                  created_at:
                    type: string
                    format: date_time
                  updated_at:
                    type: string
                    format: date_time
        '404':
          description: contact not found
    put:
      summary: Update a contact
      tags:
      - Contacts
      parameters: []
      responses:
        '200':
          description: contact updated
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                contact:
                  type: object
                  properties:
                    name:
                      type: string
                    email:
                      type: string
    delete:
      summary: Delete a contact
      tags:
      - Contacts
      responses:
        '204':
          description: contact deleted
        '404':
          description: contact not found
  "/api/v1/contacts/search":
    get:
      summary: Search contacts by tag
      tags:
      - Contacts
      parameters:
      - name: tag
        in: query
        required: true
        schema:
          type: string
      - name: page
        in: query
        required: false
        schema:
          type: integer
      - name: per_page
        in: query
        required: false
        schema:
          type: integer
      responses:
        '200':
          description: contacts found
          content:
            application/json:
              schema:
                type: object
                properties:
                  contacts:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        email:
                          type: string
                        created_at:
                          type: string
                          format: date_time
                        updated_at:
                          type: string
                          format: date_time
                  total_pages:
                    type: integer
                  current_page:
                    type: integer
                  total_entries:
                    type: integer
        '400':
          description: tag parameter missing
  "/api/v1/tags":
    get:
      summary: List tags
      tags:
      - Tags
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: integer
      - name: per_page
        in: query
        required: false
        schema:
          type: integer
      responses:
        '200':
          description: tags found
          content:
            application/json:
              schema:
                type: object
                properties:
                  tags:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        created_at:
                          type: string
                          format: date_time
                        updated_at:
                          type: string
                          format: date_time
                  total_pages:
                    type: integer
                  current_page:
                    type: integer
                  total_entries:
                    type: integer
    post:
      summary: Create a tag
      tags:
      - Tags
      parameters: []
      responses:
        '201':
          description: tag created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                tag:
                  type: object
                  properties:
                    name:
                      type: string
                  required:
                  - name
  "/api/v1/tags/{id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
    get:
      summary: Show a tag
      tags:
      - Tags
      responses:
        '200':
          description: tag found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  created_at:
                    type: string
                    format: date_time
                  updated_at:
                    type: string
                    format: date_time
        '404':
          description: tag not found
    put:
      summary: Update a tag
      tags:
      - Tags
      parameters: []
      responses:
        '200':
          description: tag updated
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                tag:
                  type: object
                  properties:
                    name:
                      type: string
    delete:
      summary: Delete a tag
      tags:
      - Tags
      responses:
        '204':
          description: tag deleted
        '404':
          description: tag not found
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
